version: '3.4'

services:
  prometheus:
    image: prom/prometheus:v2.43.1
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    ports:
      - 5430:9090
    networks:
      - my-network 
    restart: always
  
  grafana:
    image: grafana/grafana:9.5.1
    container_name: grafana
    ports:
      - 80:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"  
    restart: unless-stopped
    networks:
      - my-network 
    volumes:
      - grafana:/var/lib/grafana

  mail:
    image: bytemark/smtp
    restart: always
    container_name: mail
    networks:
      - my-network 
    environment:
      RELAY_HOST: in-v3.mailjet.com
      RELAY_PORT: 587
      RELAY_USERNAME: 
      RELAY_PASSWORD: 

  pihole:
    image: ekofr/pihole-exporter:v0.4.0
    container_name: pihole
    environment:
      - PIHOLE_API_TOKEN=
      - PIHOLE_HOSTNAME=
      - PORT=9617
    networks:
      - my-network
    restart: unless-stopped  
    ports:
      - 9617:9617
  blackbox-exporter:
    image: prom/blackbox-exporter:v0.23.0
    container_name: blackbox
    hostname: "blackbox"
    restart: always
    networks:
      - my-network
    ports:
    - 9115:9115
    volumes:
    - "./config/blackbox-exporter/blackbox-exporter.yml:/etc/prometheus/blackbox-exporter.yml"
    command:
    - "--config.file=/etc/prometheus/blackbox-exporter.yml"
  yacht:
    container_name: yacht
    restart: unless-stopped
    ports:
      - 8000:8000
    networks:
      - my-network       
    volumes:
      - yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock
    image: selfhostedpro/yacht
volumes:
  prometheus_data:
  grafana:
  yacht:

networks:
  my-network:
    external: true
    
