name: $(BuildDefinitionName)-$(SourceBranchName)-$(date:yyyyMMdd)$(Rev:.r)

pr: none

trigger:
  batch: true
  branches:
    include:
    - main

pool: docker

steps:
- script: docker-compose -p "monitoring" build
  displayName: 'Docker Compose Build'  
- script: docker-compose -p "monitoring" down
  displayName: 'Docker Compose Down'
- script: docker-compose -p "monitoring" up -d
  displayName: 'Docker Compose Up'
