name: $(BuildDefinitionName)-$(SourceBranchName)-$(date:yyyyMMdd)$(Rev:.r)

pr: none

trigger:
  batch: true
  branches:
    include:
    - main
    - develop
    - feature/*
    - renovate/*

pool: docker

steps:
  - script: docker-compose -p "monitoring" build
    displayName: "Docker Compose Build"
  - script: docker-compose -p "monitoring" down
    displayName: "Docker Compose Down"
  - script: docker-compose -p "monitoring" up -d --remove-orphans
    displayName: "Docker Compose Up"
  - script: docker system prune -f
    displayName: "Docker prune"