{
 "title": "SQL Servers",
 "description": "MSSQL Server performance metrics by Instances",
 "tags": [ "mssql" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Databases properties",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DATABASES HEALTH",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "sqlserver_server_properties",
     "query": "SELECT mean(\"total\") FROM \"State OFFLINE\" WHERE  \"type\" = 'Database properties' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "db_offline" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "ONLINE",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "sqlserver_server_properties",
     "query": "SELECT \"total\" FROM \"State ONLINE\" WHERE  \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "db_online" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "OFFLINE",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "sqlserver_server_properties",
     "query": "SELECT \"total\" FROM \"State OFFLINE\" WHERE  \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "db_offline" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "SUSPECT",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "sqlserver_server_properties",
     "query": "SELECT \"total\" FROM \"State SUSPECT\" WHERE  \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "db_suspect" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "RECOVERING",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "sqlserver_server_properties",
     "query": "SELECT \"total\" FROM \"State RECOVERING\" WHERE  \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "db_recovering" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "PENDING",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "sqlserver_server_properties",
     "query": "SELECT \"total\" FROM \"State RECOVERY_PENDING\" WHERE  \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "db_recoveryPending" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "RESTORING",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "sqlserver_server_properties",
     "query": "SELECT \"total\" FROM \"State RESTORING\" WHERE  \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "db_restoring" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "PD Full",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "sqlserver_recentbackup",
     "select": [
      [
       { "params": [ "last_full_backup_time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "database_name::tag", "operator": "=", "value": "ProjectDiary" }
     ]
    },
    { "expression": "$A * 1000", "type": "math" }
   ]
  },
  {
   "title": "Auth Full",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "sqlserver_recentbackup",
     "select": [
      [
       { "params": [ "last_full_backup_time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "database_name::tag", "operator": "=", "value": "Auth" }
     ]
    },
    { "expression": "$A * 1000", "type": "math" }
   ]
  },
  {
   "title": "PD Transaction",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "sqlserver_recentbackup",
     "select": [
      [
       {
        "params": [
         "last_transaction_log_backup_time"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "database_name::tag", "operator": "=", "value": "ProjectDiary" }
     ]
    },
    { "expression": "$A * 1000", "type": "math" }
   ]
  },
  {
   "title": "Auth Transaction",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "sqlserver_recentbackup",
     "select": [
      [
       {
        "params": [
         "last_transaction_log_backup_time"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "database_name::tag", "operator": "=", "value": "Auth" }
     ]
    },
    { "expression": "$A * 1000", "type": "math" }
   ]
  },
  {
   "title": "Total Data File Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "sqlserver_performance",
     "query": "SELECT \"total\" FROM \"Recovery Model FULL\" WHERE  \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Data File(s) Size (KB)" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" }
     ]
    }
   ]
  },
  {
   "title": "Total Log Files Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "sqlserver_performance",
     "query": "SELECT \"total\" FROM \"Recovery Model FULL\" WHERE  \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Log File(s) Size (KB)" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" }
     ]
    }
   ]
  },
  {
   "title": "Total Log Files Used Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "sqlserver_performance",
     "query": "SELECT \"total\" FROM \"Recovery Model FULL\" WHERE  \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Log File(s) Used Size (KB)" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" }
     ]
    }
   ]
  },
  {
   "title": "Memory Clerk Buffer Pool",
   "type": "stat",
   "description": "The size of the clerk, in pages, multiplied by 8KB, since each page is 8KB.",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "sqlserver_performance",
     "query": "SELECT \"total\" FROM \"Recovery Model FULL\" WHERE  \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Memory broker clerk size" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Buffer Pool" }
     ]
    }
   ]
  },
  {
   "title": "CPU Count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "sqlserver_server_properties",
     "query": "SELECT \"total\" FROM \"Recovery Model FULL\" WHERE  \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "cpu_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Quick Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Server Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "sqlserver_performance",
     "query": "SELECT \"total\" FROM \"Recovery Model FULL\" WHERE  \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Total Server Memory (KB)" }
     ]
    }
   ]
  },
  {
   "title": "Used Memory by Instance",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 6, "x": 3, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Used memory (KB)" }
     ]
    }
   ]
  },
  {
   "title": "User Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"value\") FROM \"User Connections | General Statistics\" WHERE  \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "User Connections" }
     ]
    }
   ]
  },
  {
   "title": "Buffer cache hit ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"value\") FROM \"Backup/Restore Throughput/sec | _Total | Databases\" WHERE  \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Buffer cache hit ratio" }
     ]
    }
   ]
  },
  {
   "title": "Memory Grant Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"value\") FROM \"Memory Grants Pending | Memory Manager\" WHERE  \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Memory Grants Pending" }
     ]
    }
   ]
  },
  {
   "title": "Checkpoint pages/sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"value\") FROM \"User Connections | General Statistics\" WHERE  \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Checkpoint pages/sec" }
     ]
    }
   ]
  },
  {
   "title": "Version Store Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"Average pending disk IO\") FROM \"Performance metrics\" WHERE  \"type\" = 'Performance metrics' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Version Store Size (KB)" }
     ]
    }
   ]
  },
  {
   "title": "PLE",
   "type": "stat",
   "description": "Page life expectancy",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"value\") FROM \"Page life expectancy | Buffer Manager\" WHERE  \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Page life expectancy" }
     ]
    }
   ]
  },
  {
   "title": "Backup/Restore Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"value\") FROM \"Backup/Restore Throughput/sec | _Total | Databases\" WHERE  \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Backup/Restore Throughput/sec" }
     ]
    }
   ]
  },
  {
   "title": "Active Temp Tables",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"value\") FROM \"User Connections | General Statistics\" WHERE  \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Active Temp Tables" }
     ]
    }
   ]
  },
  {
   "title": "Free List Stalls/sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT \"value\" FROM \"Free list stalls/sec | Buffer Manager\" WHERE  \"type\" = 'Performance counters' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Free list stalls/sec" }
     ]
    }
   ]
  },
  {
   "title": "Page lookups/sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"Page File Usage (%)\") FROM \"Performance metrics\" WHERE  $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Page lookups/sec" }
     ]
    }
   ]
  },
  {
   "title": "Free Space in tempdb",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"Average pending disk IO\") FROM \"Performance metrics\" WHERE  \"type\" = 'Performance metrics' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Free Space in tempdb (KB)" }
     ]
    }
   ]
  },
  {
   "title": "Database size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Data File Size by Database",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 14 },
   "format": "deckbytes",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"value\") FROM \"sqlserver_database_io\" WHERE (\"sql_instance\" =~ /^$Instance$/ AND \"file_type\" = 'ROWS') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Data File(s) Size (KB)" },
      {
       "condition": "AND",
       "key": "instance",
       "operator": "!~",
       "value": "/^(master|model|mssqlsystemresource|Total)/"
      }
     ]
    }
   ]
  },
  {
   "title": "Log File Size by Database",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 14 },
   "format": "deckbytes",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"value\") FROM \"sqlserver_database_io\" WHERE (\"sql_instance\" =~ /^$Instance$/ AND \"file_type\" = 'ROWS') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Log File(s) Size (KB)" },
      {
       "condition": "AND",
       "key": "instance",
       "operator": "!~",
       "value": "/^(master|model|mssqlsystemresource|Total)/"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "SQL Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Batch Requests/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"value\") FROM \"Batch Requests/sec | SQL Statistics\" WHERE  \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Batch Requests/sec" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "SQLServer:SQL Statistics" }
     ]
    },
    {
     "alias": "Logins/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"value\") FROM \"Logins/sec | General Statistics\" WHERE  \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Logins/sec" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "SQLServer:General Statistics" }
     ]
    },
    {
     "alias": "Logouts/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT difference(last(\"value\")) / ($__interval_ms/1000) FROM \"sqlserver_performance\" WHERE (\"sql_instance\" =~ /^$Instance$/ AND \"counter\" = 'Logouts/sec') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Logouts/sec" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "SQLServer:General Statistics" }
     ]
    },
    {
     "alias": "SQL Compilations/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT difference(last(\"value\")) / ($__interval_ms/1000) FROM \"sqlserver_performance\" WHERE (\"sql_instance\" =~ /^$Instance$/ AND \"counter\" = 'SQL Compilations/sec') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "SQL Compilations/sec" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "SQLServer:SQL Statistics" }
     ]
    },
    {
     "alias": "SQL Re-Compilations/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"value\") FROM \"SQL Re-Compilations/sec | SQL Statistics\" WHERE  \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "SQL Re-Compilations/sec" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "SQLServer:SQL Statistics" }
     ]
    },
    {
     "alias": "Processes blocked",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"value\") FROM \"Processes blocked | General Statistics\" WHERE  \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Processes blocked" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "SQLServer:General Statistics" }
     ]
    }
   ]
  },
  {
   "title": "Access Methods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_counter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "counter" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"value\") FROM \"Batch Requests/sec | SQL Statistics\" WHERE  \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "SQLServer:Access Methods" }
     ]
    }
   ]
  },
  {
   "title": "Replica/Mirroring Statistics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_counter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "counter" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"value\") FROM \"Batch Requests/sec | SQL Statistics\" WHERE  \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=~", "value": "/.*Bytes.*/" },
      { "condition": "AND", "key": "object", "operator": "!=", "value": "SQLServer:Resource Pool Stats" }
     ]
    }
   ]
  },
  {
   "title": "Databases Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Transactions/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"value\") FROM \"Transactions/sec | _Total | Databases\" WHERE  \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Transactions/sec" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" }
     ]
    },
    {
     "alias": "Write Transactions/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"value\") FROM \"Write Transactions/sec | _Total | Databases\" WHERE  \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Write Transactions/sec" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" }
     ]
    },
    {
     "alias": "Lock Timeouts/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"value\") FROM \"Lock Timeouts/sec | _Total | Locks\" WHERE  \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Lock Timeouts/sec" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" }
     ]
    },
    {
     "alias": "Number of Deadlocks/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"value\") FROM \"Number of Deadlocks/sec | _Total | Locks\" WHERE  \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Number of Deadlocks/sec" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" }
     ]
    },
    {
     "alias": "Lock Waits/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"value\") FROM \"Lock Waits/sec | _Total | Locks\" WHERE  \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Lock Waits/sec" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" }
     ]
    },
    {
     "alias": "Errors/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"value\") FROM \"Transactions/sec | _Total | Databases\" WHERE  \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Errors/sec" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" }
     ]
    }
   ]
  },
  {
   "title": "Log Flushes/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Log Flushes/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"value\") FROM \"Full Scans/sec | Access Methods\" WHERE  \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Log Flushes/sec" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" }
     ]
    }
   ]
  },
  {
   "title": "Requests completed/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Requests completed/sec" }
     ]
    }
   ]
  },
  {
   "title": "Transaction Delay",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Transaction Delay" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Transaction Delay" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" }
     ]
    }
   ]
  },
  {
   "title": "User Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "User Connections",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"value\") FROM \"Full Scans/sec | Access Methods\" WHERE  \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "User Connections" }
     ]
    }
   ]
  },
  {
   "title": "Wait Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_wait_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "wait_type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_waitstats",
     "select": [
      [
       { "params": [ "wait_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "wait_category", "operator": "=", "value": "Tran Log IO" }
     ]
    },
    {
     "alias": "$tag_wait_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "wait_type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_waitstats",
     "select": [
      [
       { "params": [ "wait_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "wait_category", "operator": "=", "value": "Other Disk IO" }
     ]
    }
   ]
  },
  {
   "title": "Errors/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Errors/sec" }
     ]
    }
   ]
  },
  {
   "title": "Memory break down",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Used memory by Instance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT * FROM \"Memory breakdown (%)\" WHERE  \"type\" = 'Memory clerk' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Used memory (KB)" }
     ]
    }
   ]
  },
  {
   "title": "Memory Clerks Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_clerk_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "clerk_type" ], "type": "tag" }
     ],
     "measurement": "sqlserver_memory_clerks",
     "query": "SELECT * FROM \"Memory breakdown (bytes)\" WHERE  $timeFilter",
     "select": [
      [
       { "params": [ "size_kb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "clerk_type", "operator": "=~", "value": "/^SQL .*/" }
     ]
    }
   ]
  },
  {
   "title": "Database I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {}
   ]
  },
  {
   "title": "IO/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Read IO/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT * FROM \"Rows read latency (ms)\" WHERE  \"type\" = 'Database stats' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Disk Read IO/sec" }
     ]
    },
    {
     "alias": "Write IO/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"value\") FROM \"sqlserver_performance\" WHERE (\"sql_instance\" =~ /^$Instance$/ AND \"counter\" = 'Disk Write IO/sec') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Disk Write IO/sec" }
     ]
    },
    {
     "alias": "Read IO Throttled/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"value\") FROM \"sqlserver_performance\" WHERE (\"sql_instance\" =~ /^$Instance$/ AND \"counter\" = 'Disk Write IO/sec') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Disk Read IO Throttled/sec" }
     ]
    },
    {
     "alias": "Write IO Throttled/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"value\") FROM \"sqlserver_performance\" WHERE (\"sql_instance\" =~ /^$Instance$/ AND \"counter\" = 'Disk Write IO/sec') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Disk Write IO Throttled/sec" }
     ]
    }
   ]
  },
  {
   "title": "IO/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Read IO/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT * FROM \"Rows read latency (ms)\" WHERE  \"type\" = 'Database stats' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Disk Read IO/sec" }
     ]
    },
    {
     "alias": "Write IO/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"value\") FROM \"sqlserver_performance\" WHERE (\"sql_instance\" =~ /^$Instance$/ AND \"counter\" = 'Disk Write IO/sec') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Disk Write IO/sec" }
     ]
    },
    {
     "alias": "Read IO Throttled/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"value\") FROM \"sqlserver_performance\" WHERE (\"sql_instance\" =~ /^$Instance$/ AND \"counter\" = 'Disk Write IO/sec') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Disk Read IO Throttled/sec" }
     ]
    },
    {
     "alias": "Write IO Throttled/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT mean(\"value\") FROM \"sqlserver_performance\" WHERE (\"sql_instance\" =~ /^$Instance$/ AND \"counter\" = 'Disk Write IO/sec') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Disk Write IO Throttled/sec" }
     ]
    }
   ]
  },
  {
   "title": "DATA | Read Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_database_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "database_name" ], "type": "tag" }
     ],
     "measurement": "sqlserver_database_io",
     "query": "SELECT * FROM \"Rows read latency (ms)\" WHERE  \"type\" = 'Database stats' AND $timeFilter",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "file_type", "operator": "=", "value": "DATA" },
      { "condition": "AND", "key": "database_name", "operator": "!~", "value": "/^(msdb|model|master)/" }
     ]
    }
   ]
  },
  {
   "title": "LOG | Read Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_database_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "database_name" ], "type": "tag" }
     ],
     "measurement": "sqlserver_database_io",
     "query": "SELECT * FROM \"Rows read latency (ms)\" WHERE  \"type\" = 'Database stats' AND $timeFilter",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "file_type", "operator": "=", "value": "LOG" },
      { "condition": "AND", "key": "database_name", "operator": "!~", "value": "/^(msdb|model|master)/" }
     ]
    }
   ]
  },
  {
   "title": "DATA | Write Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_database_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "database_name" ], "type": "tag" }
     ],
     "measurement": "sqlserver_database_io",
     "query": "SELECT * FROM \"Rows read latency (ms)\" WHERE  \"type\" = 'Database stats' AND $timeFilter",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "file_type", "operator": "=", "value": "DATA" },
      { "condition": "AND", "key": "database_name", "operator": "!~", "value": "/^(msdb|model|master)/" }
     ]
    }
   ]
  },
  {
   "title": "LOG | Write Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_database_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "database_name" ], "type": "tag" }
     ],
     "measurement": "sqlserver_database_io",
     "query": "SELECT * FROM \"Rows read latency (ms)\" WHERE  \"type\" = 'Database stats' AND $timeFilter",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "file_type", "operator": "=", "value": "LOG" },
      { "condition": "AND", "key": "database_name", "operator": "!~", "value": "/^(msdb|model|master)/" }
     ]
    }
   ]
  },
  {
   "title": "Database Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DATA | Read Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_database_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "database_name" ], "type": "tag" }
     ],
     "measurement": "sqlserver_database_io",
     "query": "SELECT * FROM \"Rows read latency (ms)\" WHERE  \"type\" = 'Database stats' AND $timeFilter",
     "select": [
      [
       { "params": [ "read_latency_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "file_type", "operator": "=", "value": "DATA" },
      { "condition": "AND", "key": "database_name", "operator": "!~", "value": "/^(msdb|model|master)/" }
     ]
    }
   ]
  },
  {
   "title": "LOG | Read Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_database_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "database_name" ], "type": "tag" }
     ],
     "measurement": "sqlserver_database_io",
     "query": "SELECT * FROM \"Rows read latency (ms)\" WHERE  \"type\" = 'Database stats' AND $timeFilter",
     "select": [
      [
       { "params": [ "read_latency_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "file_type", "operator": "=", "value": "LOG" },
      { "condition": "AND", "key": "database_name", "operator": "!~", "value": "/^(msdb|model|master)/" }
     ]
    }
   ]
  },
  {
   "title": "DATA | Write Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_database_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "database_name" ], "type": "tag" }
     ],
     "measurement": "sqlserver_database_io",
     "query": "SELECT * FROM \"Rows read latency (ms)\" WHERE  \"type\" = 'Database stats' AND $timeFilter",
     "select": [
      [
       { "params": [ "write_latency_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "file_type", "operator": "=", "value": "DATA" },
      { "condition": "AND", "key": "database_name", "operator": "!~", "value": "/^(msdb|model|master)/" }
     ]
    }
   ]
  },
  {
   "title": "LOG | Write Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_database_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "database_name" ], "type": "tag" }
     ],
     "measurement": "sqlserver_database_io",
     "query": "SELECT * FROM \"Rows read latency (ms)\" WHERE  \"type\" = 'Database stats' AND $timeFilter",
     "select": [
      [
       { "params": [ "write_latency_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "file_type", "operator": "=", "value": "LOG" },
      { "condition": "AND", "key": "database_name", "operator": "!~", "value": "/^(msdb|model|master)/" }
     ]
    }
   ]
  },
  {
   "title": "Availability Replica",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {}
   ]
  },
  {
   "title": "OUT | Bytes Sent to Replica/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "Bps", "label": "TX" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Bytes Sent to Replica/sec" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Bytes Sent to Replica/sec" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" }
     ]
    }
   ]
  },
  {
   "title": "IN | Bytes Received from Replica/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "Bps", "label": "RX" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       {
        "params": [
         "Bytes Received from Replica/sec"
        ],
        "type": "alias"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      {
       "condition": "AND",
       "key": "counter",
       "operator": "=",
       "value": "Bytes Received from Replica/sec"
      },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" }
     ]
    }
   ]
  },
  {
   "title": "Sends to Replica/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Sends to Replica/sec" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Sends to Replica/sec" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" }
     ]
    }
   ]
  },
  {
   "title": "Receives from Replica/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Receives from Replica/sec" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Receives from Replica/sec" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" }
     ]
    }
   ]
  }
 ]
}