global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

  external_labels:
      monitor: 'my-project'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
    - targets: ['prometheus-dev:9090']   

  - job_name: 'pyramidapi-dev'
    scheme: 'https'
    tls_config:
      insecure_skip_verify: true 
    scrape_interval: 10s
    scrape_timeout: 60s
    static_configs:
    - targets: ['projectpyramidapi-dev.funkysi1701.com:443']     

  - job_name: 'pyramidui-dev'
    scheme: 'https'
    tls_config:
      insecure_skip_verify: true 
    scrape_interval: 10s
    scrape_timeout: 60s
    static_configs:
    - targets: ['projectpyramid-dev.funkysi1701.com:443']         
