global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

  external_labels:
      monitor: 'my-project'

scrape_configs:
  
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
    - targets: ['prometheus:9090']

  - job_name: 'pyramidapi-prod'
    scheme: 'https'
    tls_config:
      insecure_skip_verify: true 
    scrape_interval: 30s
    static_configs:
    - targets: ['projectpyramidapi.eurosafeuk.co.uk:443']    

  - job_name: 'pyramidui-prod'
    scheme: 'https'
    tls_config:
      insecure_skip_verify: true 
    scrape_interval: 30s
    static_configs:
    - targets: ['projectpyramid.eurosafeuk.co.uk:443']  

  - job_name: 'pihole'
    static_configs:
      - targets: ['pihole:9617']        

  - job_name: "website-monitoring-http"
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
      - files:
        - /etc/prometheus/targets.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: "website-monitoring-icmp"
    metrics_path: /probe
    params:
      module: [icmp]
    file_sd_configs:
      - files:
        - /etc/prometheus/targets.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115      