apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://server04.local:5430

  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://server04.local:8086  
    user: admin
    jsonData:
      dbName: influx
    secureJsonData:
      password: admin  