apiVersion: 1

datasources:
  - name: PrometheusDev
    type: prometheus
    access: proxy
    url: http://server05.local:5431    
    
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://server05.local:8086  
    user: admin
    jsonData:
      dbName: influx
      httpMode: GET
    secureJsonData:
      password: admin  
