{
 "title": "API/Services Prod",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Requests - 2XX",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(http_requests_received_total{code=~\"2\\\\d\\\\d\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests - 400",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(http_requests_received_total{code=\"400\"})) - (sum(http_requests_received_total{code=\"400\"} offset $__range))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests - 404",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(http_requests_received_total{code=\"404\"})) - (sum(http_requests_received_total{code=\"404\"} offset $__range))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests - 405",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(http_requests_received_total{code=\"405\"})) - (sum(http_requests_received_total{code=\"405\"} offset $__range))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests - 500",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_received_total{code=\"500\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No. of HTTP Errors per Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by(code, service, controller, action) (irate(http_requests_received_total{code=~\"4\\\\d\\\\d|5\\\\d\\\\d\"}[$__range]) * 60)",
     "legendFormat": "{{code}} - {{service}} - {{controller}} - {{action}}"
    }
   ]
  },
  {
   "title": "No. of HTTP Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by(service, controller, action) (irate(http_requests_received_total[1m]) * 60)",
     "legendFormat": "{{service}} - {{controller}} - {{action}}"
    }
   ]
  },
  {
   "title": "Top 10 Slow Endpoints",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, (sum by(service, controller, action) (rate(http_request_duration_seconds_count[$__range]))))",
     "legendFormat": "{{service}} - {{action}}"
    }
   ]
  },
  {
   "title": "Top 10 Most Requested Endpoints",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, (sum by(service, controller, action) (increase(http_requests_received_total[$__range]))))",
     "legendFormat": "{{service}} - {{action}}"
    }
   ]
  },
  {
   "title": "Average Request Time",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket[1m])) by(le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Health",
   "type": "stat",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kube_service_info", "legendFormat": "{{service}}" }
   ]
  }
 ]
}