{
 "title": "Cluster Health",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"Ready\", status=\"true\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Pods Unavailable per Deployment",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_unavailable > 0",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Number of Pods in Cluster",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_pod_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pods Not Ready",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready < 1",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Top 10 Pods by CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(cluster, namespace, pod, container) (irate(container_cpu_usage_seconds_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\"}[5m])) * on (cluster, namespace, pod) group_left (node) topk by (cluster, namespace, pod) (1, max by(cluster, namespace, pod, node) (kube_pod_info{node!=\"\"}))) * 1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total CPU Usage per Node",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (sum by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))\r\n/\r\nsum by(instance) (irate(node_cpu_seconds_total[$__rate_interval])))) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top 10 Pods by Memory Usage (MB)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "topk(10, container_memory_max_usage_bytes{service=\"prometheus-kube-prometheus-kubelet\"}) / 1000000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Memory Usage per Node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "100 * (node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Disk Usage per Node",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{mountpoint=\"/\"} * 100 / node_filesystem_size_bytes{mountpoint=\"/\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}