{
 "title": "Cluster Health",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"Ready\", status=\"true\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "SLI Availability (30d)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apiserver_request:availability30d{verb=\"all\", cluster=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLI Read Availability (30d)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apiserver_request:availability30d{verb=\"read\", cluster=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLI Write Availability (30d)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apiserver_request:availability30d{verb=\"write\", cluster=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Not Ready",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready < 1",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of Pods in Cluster",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_pod_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pods Unavailable per Deployment",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_unavailable > 0",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Top 10 Pods by CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate * 100))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Top 10 Pods by Memory Usage (MB)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, max by(pod) (container_memory_usage_bytes)) / 1000000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total CPU Usage per Node",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total CPU Usage per Node",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Disk Usage per Node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{mountpoint=\"/\"} * 100 / node_filesystem_size_bytes{mountpoint=\"/\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Memory Usage per Node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "100 * (node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}