{
 "title": "API/Services",
 "tags": [
  "net",
  ".net",
  ".net core"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "url", "query": { "query": "label_values(host)" } },
   { "name": "env", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "HTTP Requests - 2XX",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(http_requests_received_total{code=~\"2\\\\d\\\\d\",host=~\"$url\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests - 400",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(http_requests_received_total{code=\"400\", host=~\"$url\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests - 404",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(http_requests_received_total{code=\"404\", host=~\"$url\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests - 405",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(http_requests_received_total{code=\"405\", host=~\"$url\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests - 409",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(http_requests_received_total{code=\"409\", host=~\"$url\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests - 500",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(http_requests_received_total{code=\"500\", host=~\"$url\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No. of HTTP Errors per Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by(code, endpoint, page) (irate(http_requests_received_total{code=~\"4\\\\d\\\\d|5\\\\d\\\\d\",host=~\"$url\"}[$__range]) * 60)",
     "legendFormat": "{{code}} - {{endpoint}} {{page}}"
    }
   ]
  },
  {
   "title": "No. of HTTP Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by(endpoint, page) (irate(http_requests_received_total{host=~\"$url\"}[1m])) * 60",
     "legendFormat": "{{endpoint}} {{page}}"
    }
   ]
  },
  {
   "title": "Top 10 Slow Endpoints",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, (sum by(endpoint, page) (rate(http_request_duration_seconds_count{host=~\"$url\"}[$__range]))))",
     "legendFormat": "{{endpoint}} {{page}}"
    }
   ]
  },
  {
   "title": "Top 10 Most Requested Endpoints",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, (sum by(endpoint, page) (increase(http_requests_received_total{host=~\"$url\"}[$__range]))))",
     "legendFormat": "{{endpoint}} {{page}}"
    }
   ]
  },
  {
   "title": "Average Request Time",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{host=~\"$url\"}[1m])) by(le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}