{
 "title": "API/Services",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Requests - 2XX",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(http_requests_received_total{code=~\"2\\\\d\\\\d\",namespace=~\"$namespace\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests - 400",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(http_requests_received_total{code=\"400\", namespace=~\"$namespace\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests - 404",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(http_requests_received_total{code=\"404\", namespace=~\"$namespace\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests - 405",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(http_requests_received_total{code=\"405\", namespace=~\"$namespace\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests - 409",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(http_requests_received_total{code=\"409\", namespace=~\"$namespace\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests - 500",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(http_requests_received_total{code=\"500\", namespace=~\"$namespace\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No. of HTTP Errors per Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by(code, service, controller, action) (irate(http_requests_received_total{code=~\"4\\\\d\\\\d|5\\\\d\\\\d\",namespace=~\"$namespace\"}[$__range]) * 60)",
     "legendFormat": "{{code}} - {{service}} - {{controller}} - {{action}}"
    }
   ]
  },
  {
   "title": "No. of HTTP Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by(service, controller, action) (irate(http_requests_received_total{namespace=~\"$namespace\"}[1m]) * 60)",
     "legendFormat": "{{controller}} - {{action}}"
    }
   ]
  },
  {
   "title": "Top 10 Slow Endpoints",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, (sum by(service, controller, action) (rate(http_request_duration_seconds_count{namespace=~\"$namespace\"}[$__range]))))",
     "legendFormat": "{{controller}} - {{action}}"
    }
   ]
  },
  {
   "title": "Top 10 Most Requested Endpoints",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, (sum by(service, controller, action) (increase(http_requests_received_total{namespace=~\"$namespace\"}[$__range]))))",
     "legendFormat": "{{controller}} - {{action}}"
    }
   ]
  },
  {
   "title": "Average Request Time",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{namespace=~\"$namespace\"}[1m])) by(le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}