draft: false
acme:
  email_account: funkysi1701@gmail.com
  staging: false
  certs_permissions:
    files_mode: 0644
    dirs_mode: 0755
profiles:
- name: profile
  provider: cloudflare
  provider_options:
    auth_token: ${auth_token}
    zoneid: 7f7ed64b3c12075d64b61d0232399026
certificates:
- name: helloworld2.funkysi1701.com
  domains:
  - "helloworld2.funkysi1701.com"
  profile: profile
- name: dashboards2.funkysi1701.com
  domains:
  - "dashboards2.funkysi1701.com"
  profile: profile  