draft: false
acme:
  email_account: funkysi1701@gmail.com
  staging: true
profiles:
- name: profile
  provider: cloudflare
  provider_options:
    auth_token: ${auth_token}
    zoneid: 7f7ed64b3c12075d64b61d0232399026
certificates:
- domains:
  - helloworld.funkysi1701.com
  - grafana.funkysi1701.com
  - yacht.funkysi1701.com
  profile: profile