draft: false
acme:
  email_account: funkysi1701@gmail.com
  staging: true
profiles:
- name: profile
  provider: cloudflare
  provider_options:
    auth_token: au5sL4P_RDSXQ3oJcfW5VlLqxxgmTw_Lw4cYF9BR
    zoneid: 7f7ed64b3c12075d64b61d0232399026
certificates:
- domains:
  - helloworld2.funkysi1701.com
  - pig.funkysi1701.com
  profile: profile